[workspace]
resolver = "2"
members = ["packages/cli", "packages/core", "packages/utils"]

[patch.crates-io]
shirabe-utils = { path = "packages/utils" }

[profile.release]
lto = true
codegen-units = 1
painc = "abort"
