[package]
name = "shirabe-utils"
version = "0.1.0"
edition = "2024"
authors = ["hanasaki <hanasakayui2022@gmail.com>"]
description = "Utilities for the Shirabe Framework"
keywords = ["shirabe", "bot", "utils"]
categories = ["logging", "development-tools"]
license = "MIT"
repository = "https://github.com/shirabe-rs/shirabe"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
